modLoader="javafml"
loaderVersion="${loader_version_range}"
license="${mod_license}"

[[mods]]
modId="mcaichat"
version="${mod_version}"
displayName="MC-AI Chat"
displayURL="https://github.com/thanwiggins/mcaichat"
authors="ThanWiggins"
description='''${mod_description}'''

[[dependencies.${mod_id}]]
    modId="forge"
    mandatory=true
    versionRange="${forge_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.${mod_id}]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_version_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.mcaichat]]
    modId="structurify"
    mandatory=true
    versionRange="[2.0.28,)"
    ordering="AFTER"
    side="BOTH"